cluster:
  "bsub -P acc_untreatedIBD \
    -q {resources.queue} \
    -J smk-{rule} \
    -n {threads} \
    -R 'span[hosts=1]' \
    -M {resources.mem_mb} \
    -W {resources.time} \
    -o logs/{jobid}_%J.out \
    -e logs/{jobid}_%J.err"

default-resources:
  threads: 8
  time: 1:00
  queue: express
  mem_mb: 16_000

restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 8
latency-wait: 120
jobs: 1000
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: conda

