site_name: Sopa
repo_name: gustaveroussy/sopa
repo_url: https://github.com/gustaveroussy/sopa
copyright: Copyright &copy; 2023 - 2024 Quentin Blampey
theme:
  name: material
  logo: assets/sopa_small_white.png
  favicon: assets/sopa_favicon.png
  features:
    - content.code.annotate
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials:
    - API usage: tutorials/api_usage.ipynb
    - Snakemake pipeline: tutorials/snakemake.md
    - CLI usage: tutorials/cli_usage.md
    - Xenium Explorer usage: tutorials/xenium_explorer/explorer.ipynb
    - Align images (e.g. H&E): tutorials/align.md
    - Spatial statistics: tutorials/spatial.ipynb
    - Visium HD usage: tutorials/visium_hd.ipynb
    - H&E usage: tutorials/he.ipynb
    - Advanced segmentation: tutorials/advanced_segmentation.md
    - Other segmentation methods:
      - ComSeg: tutorials/comseg.ipynb
  - API:
    - Readers: api/readers.md
    - Patches: api/patches.md
    - Segmentation: api/segmentation.md
    - Utils: api/utils.md
    - Spatial operations: api/spatial.md
    - Misc: api/misc.md
  - CLI: cli.md
  - Frequently asked questions: faq.md
  - Cite us: cite_us.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 4
  - mkdocs-jupyter:
      include_source: True
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
