executor: slurm
default-resources:
    slurm_partition: cpu_short # your default partition
    mem_mb: 8000
    gpu: 0
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
