# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/master/workflow/config/example_commented.yaml
read:
  technology: visium_hd

patchify:
  patch_width_pixel: 2000
  patch_overlap_pixel: 50

segmentation:
  cellpose:
    diameter: 15
    channels: ["r"] # first channel of the H&E image
    min_area: 50

aggregate:
  aggregate_channels: false
  aggregate_genes: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

explorer:
  ram_threshold_gb: 4
