executor: lsf

default-resources:
  mem_mb: 8_000
  lsf_project: acc_untreatedIBD
  lsf_queue: premium
  walltime: 90

resource_mapping:
  threads: "-n {threads}"
  walltime: "-W {resources.walltime}"

set-resources:
  explorer:
      mem_mb: 256_000
  image_write:
      mem_mb: 64_000
  to_spatialdata:
      mem_mb: 128_000
  patch_segmentation_baysor:
      mem_mb: 128_000
  aggregate:
      mem_mb: 64_000
  patchify_transcripts:
      mem_mb: 32_000
  report:
      mem_mb: 32_000
  annotate:
      mem_mb: 64_000
      lsf_queue: gpu
      lsf_extra: "'-R select[h100nvl] -gpu num=1'"

restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: conda
