# Warning: this profile is still experimental.

executor: lsf
default-resources:
    mem_mb: 8_000 # default rules memory in MB (you can keep this value)
    gpu: 0

# other options (you can keep the default values)
restart-times: 0
max-jobs-per-second: 100
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 50
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
