lsf:
  project: acc_untreatedIBD  # Default project for all jobs
  queue: premium             # Default queue
  __default__:
    runtime: 60              # Default runtime in minutes
    mem_mb: 4096             # Default memory
  resources:
    - "queue=queue"          # Map resource param to LSF -q
    - "project=project"      # Map resource param to LSF -P
  output: "logs/%(jobid)s.out"
  error: "logs/%(jobid)s.err"
  jobname: "smk.%(rulename)s.%(jobid)s"
  extras: |
    -J smk.%(rulename)s.%(jobid)s
    -cwd

