# Using the 10X Genomics multi-channel segmentation as a prior for Baysor.

# For parameters details, see this commented example: https://github.com/gustaveroussy/sopa/blob/master/workflow/config/example_commented.yaml
read:
  technology: xenium

patchify:
  patch_width_microns: -1 # only one patch
  patch_overlap_microns: 0

segmentation:
  proseg:
    prior_shapes_key: cell_id # this allows to use the prior segmentation performed by 10X Genomics
    unassigned_value: UNASSIGNED

aggregate:
  aggregate_channels: true
  min_transcripts: 10 # [optional] cells whose transcript count is below that this threshold are filtered

# Comment this out if you want to use tangram -->

# annotation:
#   method: tangram
#   args:
#     sc_reference_path: "..."
#     cell_type_key: ct

explorer:
  gene_column: "feature_name"
  ram_threshold_gb: 4
