name: ci
on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master, dev]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  build:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11.8", "3.12"]
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      #----------------------------------------------
      #         install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      #----------------------------------------------
      #             install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --extras "dev cellpose wsi" --no-interaction && poetry run pip install snakemake 'pulp<2.8'

      #----------------------------------------------
      #              perform tasks
      #----------------------------------------------
      - name: Tests
        run: poetry run pytest

      - name: Snakemake
        run: cd workflow && poetry run snakemake --config sdata_path=tuto.zarr --configfile=config/toy/cellpose.yaml --workflow-profile profile/ci -c1

      - name: Deploy doc
        if: contains(github.ref, 'tags')
        run: poetry run mkdocs gh-deploy --force

  publish:
    needs: [build]
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.17
        with:
          python_version: "3.10"
          pypi_token: ${{ secrets.PYPI_TOKEN }}
