name: ci

on:
  push:
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  tests:
    needs: [pre-commit]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install extra dependencies
        run: uv sync --extra cellpose --extra wsi --dev && uv run pip install snakemake

      - name: Tests
        run: uv run pytest

      - name: Snakemake
        run: cd workflow && uv run snakemake --config sdata_path=tuto.zarr --configfile=config/toy/cellpose.yaml --workflow-profile profile/ci -c1

  deploy-docs:
    needs: [tests]
    if: contains(github.ref, 'tags')
    name: "Deploy documentation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Build documentation
        run: uv run mkdocs gh-deploy --force

  pypi-release:
    needs: [tests]
    if: contains(github.ref, 'tags')
    name: "PyPI release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_TOKEN }}
